### ISSUE TITLE
Building Segmentation Proof of Concept

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/aerial-segmentation#15]
## Tasks

- [x] Create a COCO dataset from the Chatswood buildings dataset on [SharePoint](https://unisyd.sharepoint.com/:f:/r/teams/SydneyInformaticsHub2/Shared%20Documents/1%20SIH%20Central%20Document%20Repository/Projects/1%20JIRA%20projects/PIPE-3956%20Urban%20Heat%20Islands/data/[chatswood](https://unisyd.sharepoint.com/:f:/r/teams/SydneyInformaticsHub2/Shared%20Documents/1%20SIH%20Central%20Document%20Repository/Projects/1%20JIRA%20projects/PIPE-3956%20Urban%20Heat%20Islands/data/chatswood?csf=1&web=1&e=QUbhJd)?csf=1&web=1&e=QUbhJd) using the gis2coco conversion script
- [x] Upload Chatswood buildings COCO to Roboflow
- [x] Use updated detectron2 fine tuning notebook to fine tune a model on this dataset
- [x] Report back performance
- [x] If performance looks good, save the model weights and put them on sharepoint in a new folder for models in the main project folder
- [ ] Export a tensorflow weights object from pytorch as well, and test to see if the tensorflow converted weights can be used for inference/prediction.
- [x] Implement a gradio application deployed on huggingface spaces demonstrating functionality of the building detector. This app should use leaflet to pull in data run inference on sixmaps aerial imagery.

**Comment by sahandv** [comment]
> ## Tasks
> * [x]  Create a COCO dataset from the Chatswood buildings dataset on [SharePoint](https://unisyd.sharepoint.com/:f:/r/teams/SydneyInformaticsHub2/Shared%20Documents/1%20SIH%20Central%20Document%20Repository/Projects/1%20JIRA%20projects/PIPE-3956%20Urban%20Heat%20Islands/data/%5Bchatswood%5D(https://unisyd.sharepoint.com/:f:/r/teams/SydneyInformaticsHub2/Shared%20Documents/1%20SIH%20Central%20Document%20Repository/Projects/1%20JIRA%20projects/PIPE-3956%20Urban%20Heat%20Islands/data/chatswood?csf=1&web=1&e=QUbhJd)?csf=1&web=1&e=QUbhJd) using the gis2coco conversion script
> * [x]  Upload Chatswood buildings COCO to Roboflow

Links to Roboflow:

[Roboflow SD](https://universe.roboflow.com/sih-vpfnf/gis-pinm8)

[Roboflow HD](https://universe.roboflow.com/sih-vpfnf/gis-hd)

**Comment by hlydecker** [comment]
Nice work!
