### ISSUE TITLE
Feature: convert detectron2 pytorch weights to onnx

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/aerial-segmentation#19]
## Context

Detecron2 pytorh weights are very heavy and require nasty detectron2 dependencies to work with. For lightweight deployments we should convert fitted model weights into forms we can more easily use with scalable compute on edge.

## Tasks

- [x] Load fitted detectron2 maskrcnn model weights for the chatswood buildings sample. Model weights are on sharepoint.
- [x] Identify best format to convert into for light weight edge inference (ONNX might be good).
- [x] Figure out how to export detectron2 weights into the chosen lightweight format. See this discussion on the detectron2 repo: https://github.com/facebookresearch/detectron2/issues/4414 as well as the detectron2 export python script.
- [ ] Implement conversion / model export script.
