### ISSUE TITLE
Courtyard detection

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/aerial-segmentation#44]
## Context

Currently our building detection models are drawing out segmentations where any voids in the interior geometry of a building are considered part of the building's footprint:

<img width="379" alt="image" src="https://github.com/Sydney-Informatics-Hub/aerial-segmentation/assets/50643975/db4530bf-b95e-41cd-aade-d4369d38e18e">

This is a problem as these voids likely have impacts on thermal characteristics.

## Tasks

- [ ] Research possible solutions for this.
- [ ] Attempt to use RLE COCO annotations accounting for voids. According to discussion in the issues on the detectron2 repo, this apparently still won't fix the problem? But worth a shot.
- [ ] Create a training dataset of courtyards / interior voids, and train a model to detect voids. I suspect this model will have numerous serious problems.
- [ ] Investigate and attempt any other approaches as they are identified.
